AWSTemplateFormatVersion: "2010-09-09"
Description: Mackerel Example Stacks

Parameters:
  projectName:
    Type: String
    Default: mackerel
    Description: "Resource prefix"
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9]*"
  # ssh-key
  eC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Default: "mackerel-key"

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 01_vpc.yml
      Parameters:
        projectName: !Ref projectName

  EFS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 05_efs.yml
      Parameters:
        projectName: !Ref projectName
        vpc: !GetAtt VPC.Outputs.vpc
        subnet: !GetAtt VPC.Outputs.publicSubnet1

  SSHGate:
    Type: AWS::CloudFormation::Stack
    DependsOn: EFS
    Properties:
      TemplateURL: 02_ssh_gate.yml
      Parameters:
        projectName: !Ref projectName
        vpc: !GetAtt VPC.Outputs.vpc
        eC2KeyPair: !Ref eC2KeyPair
        publicSubnet: !GetAtt VPC.Outputs.publicSubnet1
        EFSFileSystem: !GetAtt EFS.Outputs.EFSFileSystem

  Lambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 03_lambda.yml
      Parameters:
        projectName: !Ref projectName
        vpc: !GetAtt VPC.Outputs.vpc
        publicSubnet1: !GetAtt VPC.Outputs.publicSubnet1
        publicSubnet2: !GetAtt VPC.Outputs.publicSubnet2
        privateSubnet1: !GetAtt VPC.Outputs.privateSubnet1

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 04_ecs.yml
      Parameters:
        projectName: !Ref projectName
        vpc: !GetAtt VPC.Outputs.vpc
        publicSubnet1: !GetAtt VPC.Outputs.publicSubnet1
        publicSubnet2: !GetAtt VPC.Outputs.publicSubnet2
        privateSubnet1: !GetAtt VPC.Outputs.privateSubnet1

  CLB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 06_clb.yml
      Parameters:
        projectName: !Ref projectName
        vpc: !GetAtt VPC.Outputs.vpc
        publicSubnet1: !GetAtt VPC.Outputs.publicSubnet1
        publicSubnet2: !GetAtt VPC.Outputs.publicSubnet2
        privateSubnet1: !GetAtt VPC.Outputs.privateSubnet1
  Elasticache:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 07_elasticache.yml
      Parameters:
        projectName: !Ref projectName
        vpc: !GetAtt VPC.Outputs.vpc
        publicSubnet1: !GetAtt VPC.Outputs.publicSubnet1
        publicSubnet2: !GetAtt VPC.Outputs.publicSubnet2
        privateSubnet1: !GetAtt VPC.Outputs.privateSubnet1

  SQS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 08_sqs.yml
      Parameters:
        projectName: !Ref projectName
        vpc: !GetAtt VPC.Outputs.vpc
        publicSubnet1: !GetAtt VPC.Outputs.publicSubnet1
        publicSubnet2: !GetAtt VPC.Outputs.publicSubnet2
        privateSubnet1: !GetAtt VPC.Outputs.privateSubnet1
        MyPublishUserPassword: "qwerty1"
        MyQueueUserPassword: "qwerty2"

  STEP:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 09_stepFunc.yml
      Parameters:
        projectName: !Ref projectName

  BATCH:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 10_batch.yml
      Parameters:
        projectName: !Ref projectName
        KeyPair: !Ref eC2KeyPair
        publicSubnet1: !GetAtt VPC.Outputs.publicSubnet1
        vpc: !GetAtt VPC.Outputs.vpc
Outputs:
  SSHGateIP:
    Value: !GetAtt SSHGate.Outputs.SSHGateIP
  LambdaURL:
    Value: !GetAtt Lambda.Outputs.LambdaURL
  NginxURL:
    Value: !GetAtt ECS.Outputs.NginxURL
  CLBURL:
    Value: !GetAtt CLB.Outputs.CLBURL
