AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  projectName:
    Type: String
  vpc:
    Type: String
  # ssh-key
  eC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
  publicSubnet:
    Type: String
  EFSFileSystem:
    Type: String

Resources:
  ec2Securitygroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${projectName}-ec2-sg
      GroupDescription: !Sub ${projectName}-ec2-sg
      Tags:
        - Key: Name
          Value: !Sub ${projectName}-ec2-sg
      VpcId: !Ref vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"

  # EC2WaitHandle:
  #   Type: AWS::CloudFormation::WaitConditionHandle
  # EC2WaitCondition:
  #   Type: AWS::CloudFormation::WaitCondition
  #   DependsOn: sshGate
  #   Properties:
  #     Handle: !Ref 'EC2WaitHandle'
  #     Timeout: '300'


  sshGate:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-08111162
      InstanceType: t2.micro
      KeyName: !Ref eC2KeyPair
      SecurityGroupIds:
        - !Ref ec2Securitygroup
      SubnetId: !Ref publicSubnet
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          #/opt/aws/bin/cfn-init -s ${AWS::StackName} -r EC2 --region ${AWS::Region}
          #yum install -y nfs-utils
          yum install -y amazon-efs-utils
          mkdir /mnt/public
          echo "${EFSFileSystem}:/ /mnt/public efs tls,_netdev" >> /etc/fstab
          mount -a -t efs defaults
          chown ec2-user:ec2-user /mnt/public
      #mount -t nfs4 -o nfsvers=4.1 ${EFSFileSystem}.efs.${AWS::Region}.amazonaws.com:/ /mnt/public
      #/opt/aws/bin/cfn-signal -e $? -r "efs mount complete" ${EC2WaitHandle} 
      Tags:
        - Key: Name
          Value: !Sub ${projectName}-ec2
Outputs:
  SSHGateIP:
    Value: !GetAtt sshGate.PublicIp
