AWSTemplateFormatVersion: "2010-09-09"
Description: "test"
Resources:
    # ファイアウォールの作成
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Enable HTTP access on the configured port
            SecurityGroupIngress:
                IpProtocol: tcp
                FromPort: 80
                ToPort: 80
                CidrIp: '0.0.0.0/0'
    # 起動処理の作成
    LaunchConfig:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties:
            ImageId: ami-c229c0a2
            InstanceType: t2.nano
            SecurityGroups: 
                - !Ref 'InstanceSecurityGroup'
            UserData: !Base64
                Fn::Join:
                    - ''
                    -   - "#!/bin/bash -xe\n"
                        - "yum update -y aws-cfn-bootstrap\n"
                        - '/opt/aws/bin/cfn-init -v '
                        - '         --stack '
                        - !Ref 'AWS::StackName'
                        - '         --resource LaunchConfig '
                        - '         --region '
                        - !Ref 'AWS::Region'
                        - "\n"
                        - '/opt/aws/bin/cfn-signal -e $? '
                        - '         --stack '
                        - !Ref 'AWS::StackName'
                        - '         --resource WebServerGroup '
                        - '         --region '
                        - !Ref 'AWS::Region'
                        - "\n"
        Metadata:
            Comment: Install a simple application
            AWS::CloudFormation::Init:
                config:
                    packages:
                        yum:
                            httpd: []
                    files:
                        /var/www/html/index.html:
                            content: !Join

