AWSTemplateFormatVersion: '2010-09-09'
Description: Mackerel Example Stacks
Parameters:
  projectName:
    Type: String
    Default: mackerel
    Description: Resource prefix
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9]*
  eC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Default: mackerel-test
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-1.amazonaws.com/mackerel-bucket/995375836b7698a0a2dcd02b3c79bed4.template
      Parameters:
        projectName:
          Ref: projectName
  SSHGate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-1.amazonaws.com/mackerel-bucket/7ea40b4cbf587c4f84c1e82edb172cae.template
      Parameters:
        projectName:
          Ref: projectName
        vpc:
          Fn::GetAtt:
          - VPC
          - Outputs.vpc
        eC2KeyPair:
          Ref: eC2KeyPair
        publicSubnet:
          Fn::GetAtt:
          - VPC
          - Outputs.publicSubnet1
  Lambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-1.amazonaws.com/mackerel-bucket/18aa673fb7a0069878c368fa0daf2983.template
      Parameters:
        projectName:
          Ref: projectName
        vpc:
          Fn::GetAtt:
          - VPC
          - Outputs.vpc
        publicSubnet1:
          Fn::GetAtt:
          - VPC
          - Outputs.publicSubnet1
        publicSubnet2:
          Fn::GetAtt:
          - VPC
          - Outputs.publicSubnet2
        privateSubnet1:
          Fn::GetAtt:
          - VPC
          - Outputs.privateSubnet1
Outputs:
  SSHGateIP:
    Value:
      Fn::GetAtt:
      - SSHGate
      - Outputs.SSHGateIP
  LambdaURL:
    Value:
      Fn::GetAtt:
      - Lambda
      - Outputs.LambdaURL
