AWSTemplateFormatVersion: '2010-09-09'
Description: Mackerel Example Stacks
Parameters:
  projectName:
    Type: String
    Default: mackerel
    Description: Resource prefix
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9]*
  eC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Default: mackerel-key
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/mackerel-bucket2/75b1e7a02108dd5fecfc6b51a1a77e77.template
      Parameters:
        projectName:
          Ref: projectName
  BATCH:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/mackerel-bucket2/2d5a5d57025c4d8a85350b93dbcd6b60.template
      Parameters:
        projectName:
          Ref: projectName
        KeyPair:
          Ref: eC2KeyPair
        publicSubnet1:
          Fn::GetAtt:
          - VPC
          - Outputs.publicSubnet1
        vpc:
          Fn::GetAtt:
          - VPC
          - Outputs.vpc
