AWSTemplateFormatVersion: '2010-09-09'
Description: Mackerel Example Stacks

Parameters:
  projectName:
    Type: String
    Default: mackerel
    Description: Resource prefix
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9]*
  # ssh-key
  eC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Default: mackerel-key

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-1.amazonaws.com/mackerel-bucket/4a80c3b47a37057dfea8b0dc8b3dcb8a.template
      Parameters:
        projectName:

          Ref: projectName
  EFS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-1.amazonaws.com/mackerel-bucket/7f7775b7efeb7ff3d4d70fa6bfad927b.template
      Parameters:
        projectName:
          Ref: projectName
        vpc:
          Fn::GetAtt:
          - VPC
          - Outputs.vpc
        subnet:

          Fn::GetAtt:
          - VPC
          - Outputs.publicSubnet1
  SSHGate:
    Type: AWS::CloudFormation::Stack
    DependsOn: EFS
    Properties:
      TemplateURL: https://s3.ap-southeast-1.amazonaws.com/mackerel-bucket/f6f6ddac9d10065889b0023aa7ec2f8c.template
      Parameters:
        projectName:
          Ref: projectName
        vpc:
          Fn::GetAtt:
          - VPC
          - Outputs.vpc
        eC2KeyPair:
          Ref: eC2KeyPair
        publicSubnet:
          Fn::GetAtt:
          - VPC
          - Outputs.publicSubnet1
        EFSFileSystem:

  # Lambda:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: 03_lambda.yml
  #     Parameters:
  #       projectName: !Ref projectName
  #       vpc: !GetAtt VPC.Outputs.vpc
  #       publicSubnet1: !GetAtt VPC.Outputs.publicSubnet1
  #       publicSubnet2: !GetAtt VPC.Outputs.publicSubnet2
  #       privateSubnet1: !GetAtt VPC.Outputs.privateSubnet1
  # ECS:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: 04_ecs.yml
  #     Parameters:
  #       projectName: !Ref projectName
  #       vpc: !GetAtt VPC.Outputs.vpc
  #       publicSubnet1: !GetAtt VPC.Outputs.publicSubnet1
  #       publicSubnet2: !GetAtt VPC.Outputs.publicSubnet2
  #       privateSubnet1: !GetAtt VPC.Outputs.privateSubnet1
          Fn::GetAtt:
          - EFS
          - Outputs.EFSFileSystem
  CLB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-1.amazonaws.com/mackerel-bucket/e85184978a96db5490161136bff613d0.template
      Parameters:
        projectName:
          Ref: projectName
        vpc:
          Fn::GetAtt:
          - VPC
          - Outputs.vpc
        publicSubnet1:
          Fn::GetAtt:
          - VPC
          - Outputs.publicSubnet1
        publicSubnet2:
          Fn::GetAtt:
          - VPC
          - Outputs.publicSubnet2
        privateSubnet1:

          Fn::GetAtt:
          - VPC
          - Outputs.privateSubnet1
Outputs:
  SSHGateIP:
    Value:
  # LambdaURL:
  #   Value: !GetAtt Lambda.Outputs.LambdaURL
  # NginxURL:
  #   Value: !GetAtt ECS.Outputs.NginxURL
      Fn::GetAtt:
      - SSHGate
      - Outputs.SSHGateIP
