AWSTemplateFormatVersion: '2010-09-09'
Description: Mackerel Example Stacks
Parameters:
  projectName:
    Type: String
    Default: mackerel
    Description: Resource prefix
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9]*
  eC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Default: mackerel-key
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/mackerel-bucket2/75b1e7a02108dd5fecfc6b51a1a77e77.template
      Parameters:
        projectName:
          Ref: projectName
  KDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/mackerel-bucket2/9c23bc46f915c9c56f10b9c2ef07facd.template
      Parameters:
        projectName:
          Ref: projectName
        KeyName:
          Ref: eC2KeyPair
        vpc:
          Fn::GetAtt:
          - VPC
          - Outputs.vpc
        subnet:
          Fn::GetAtt:
          - VPC
          - Outputs.publicSubnet1
